package vista;
//Desarrollo del módulo de gestión de pacientes
import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPaciente.class.getName());

    
    public FrmPaciente() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestión de Pacientes");
        MostrarPacientes();
        LimpiarCampos();
        
        tblPacientes.getColumnModel().getColumn(0).setPreferredWidth(30);   // ID
        tblPacientes.getColumnModel().getColumn(1).setPreferredWidth(100);  // Nombre
        tblPacientes.getColumnModel().getColumn(2).setPreferredWidth(100);  // Apellido
        tblPacientes.getColumnModel().getColumn(3).setPreferredWidth(80);   // DNI
        tblPacientes.getColumnModel().getColumn(4).setPreferredWidth(70);   // Sexo
        tblPacientes.getColumnModel().getColumn(5).setPreferredWidth(100);  // Teléfono
        tblPacientes.getColumnModel().getColumn(6).setPreferredWidth(180);  // Correo
        tblPacientes.getColumnModel().getColumn(7).setPreferredWidth(120);  // Dirección
    }
    
    private void LimpiarCampos() {

    txtNombre.setText("");
    txtApellido.setText("");
    txtDni.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");
    txtDireccion.setText("");

    cmbSexo.setSelectedIndex(0);
}
    
    private void MostrarPacientes() {

    try {

        ConexionBD conexionBD = new ConexionBD();
        Connection con = conexionBD.conectar();

        String sql = "SELECT * FROM paciente";

        PreparedStatement ps = con.prepareStatement(sql);

        ResultSet rs = ps.executeQuery();

        DefaultTableModel modelo = (DefaultTableModel) tblPacientes.getModel();

        modelo.setRowCount(0);

        while (rs.next()) {

            Object fila[] = {

                rs.getInt("idPaciente"),
                rs.getString("nombre"),
                rs.getString("apellido"),
                rs.getString("dni"),
                rs.getString("sexo"),
                rs.getString("telefono"),
                rs.getString("correo"),
                rs.getString("direccion")

            };

            modelo.addRow(fila);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombres:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Correo:");

        jLabel7.setText("Dirección:");

        txtNombre.setName("txtNombre"); // NOI18N

        txtApellido.setName("txtApellido"); // NOI18N

        txtDni.setName("txtDni"); // NOI18N

        txtTelefono.setName("txtTelefono"); // NOI18N

        txtCorreo.setName("txtCorreo"); // NOI18N

        txtDireccion.setName("txtDireccion"); // NOI18N

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cmbSexo.setName("cmbSexo"); // NOI18N

        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.setName("btnActualizar"); // NOI18N
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setName("btnLimpiar"); // NOI18N
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "DNI", "Sexo", "Teléfono", "Correo", "Dirección"
            }
        ));
        tblPacientes.setName("tblPacientes"); // NOI18N
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtApellido)
                            .addComponent(txtDni)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(15, 15, 15)
                                .addComponent(btnActualizar)
                                .addGap(29, 29, 29)
                                .addComponent(btnEliminar)
                                .addGap(26, 26, 26)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

        ConexionBD conexionBD = new ConexionBD();
        Connection con = conexionBD.conectar();

        String sql =
            "INSERT INTO paciente "
          + "(nombre, apellido, dni, sexo, telefono, correo, direccion) "
          + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setString(1, txtNombre.getText());
        ps.setString(2, txtApellido.getText());
        ps.setString(3, txtDni.getText());
        ps.setString(4, cmbSexo.getSelectedItem().toString());
        ps.setString(5, txtTelefono.getText());
        ps.setString(6, txtCorreo.getText());
        ps.setString(7, txtDireccion.getText());

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Paciente registrado correctamente");

    } catch (Exception e) {

        if (e.getMessage().contains("Duplicate entry")) {

        JOptionPane.showMessageDialog(this, "Ya existe un paciente registrado con ese DNI");

    } else {

        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
           LimpiarCampos();  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {

        ConexionBD conexionBD = new ConexionBD();
        Connection con = conexionBD.conectar();

        String sql = "SELECT * FROM paciente WHERE dni = ?";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setString(1, txtDni.getText());

        ResultSet rs = ps.executeQuery();

    if (rs.next()) {

        txtNombre.setText(rs.getString("nombre"));
        txtApellido.setText(rs.getString("apellido"));
        cmbSexo.setSelectedItem(rs.getString("sexo"));
        txtTelefono.setText(rs.getString("telefono"));
        txtCorreo.setText(rs.getString("correo"));
        txtDireccion.setText(rs.getString("direccion"));

    } else {

        JOptionPane.showMessageDialog(this, "Paciente no encontrado");

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

}   
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         try {

    ConexionBD conexionBD = new ConexionBD();
    Connection con = conexionBD.conectar();

    String sql =
            "UPDATE paciente SET "
            + "nombre = ?, "
            + "apellido = ?, "
            + "sexo = ?, "
            + "telefono = ?, "
            + "correo = ?, "
            + "direccion = ? "
            + "WHERE dni = ?";

    PreparedStatement ps =
            con.prepareStatement(sql);

    ps.setString(1, txtNombre.getText());
    ps.setString(2, txtApellido.getText());
    ps.setString(3, cmbSexo.getSelectedItem().toString());
    ps.setString(4, txtTelefono.getText());
    ps.setString(5, txtCorreo.getText());
    ps.setString(6, txtDireccion.getText());

    ps.setString(7, txtDni.getText());

    int filas = ps.executeUpdate();

    if (filas > 0) {

        JOptionPane.showMessageDialog(
                this,
                "Paciente actualizado correctamente");

        MostrarPacientes();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el paciente");

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

}
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea eliminar este paciente?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }
        
        try {

        ConexionBD conexionBD = new ConexionBD();
        Connection con = conexionBD.conectar();

        String sql = "DELETE FROM paciente WHERE dni = ?";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setString(1, txtDni.getText());

        int filas = ps.executeUpdate();

        if (filas > 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Paciente eliminado correctamente");

            MostrarPacientes();
            LimpiarCampos();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No existe un paciente con ese DNI");
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,"Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        int fila = tblPacientes.getSelectedRow();

        txtNombre.setText(tblPacientes.getValueAt(fila, 1).toString());
        txtApellido.setText(tblPacientes.getValueAt(fila, 2).toString());
        txtDni.setText(tblPacientes.getValueAt(fila, 3).toString());

        cmbSexo.setSelectedItem(tblPacientes.getValueAt(fila, 4).toString());

        txtTelefono.setText(tblPacientes.getValueAt(fila, 5).toString());
        txtCorreo.setText(tblPacientes.getValueAt(fila, 6).toString());
        txtDireccion.setText(tblPacientes.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tblPacientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPaciente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
